import React from "react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import type { Metadata } from "next";
import Hybox from "@/layout/Tutorial/HyboxTutor";

export const metadata: Metadata = {
  title: "Olativity",
  description: "Generated by create next app",
  icons: {
    icon: "/img/SC.png",
  },
};

function tutorialPage() {
  return (
    <>
      <Navbar />
      <main>
        <Hybox />
      </main>
      <Footer />
    </>
  );
}

export default tutorialPage;
