import Image from "next/image";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Hero from "@/layout/Hero";
import type { Metadata } from "next";

import About from "@/layout/About";

export const metadata: Metadata = {
  title: "Olativity",
  description: "Generated by create next app",
  icons: {
    icon: "/img/SC.png",
  },
};

export default function Home() {
  return (
    <>
      <Navbar />
      <main>
        <Hero />
        <About />
      </main>
      <Footer />
    </>
  );
}
